package com.sucho.placepicker

object Constants {
  const val SHOW_LAT_LONG_INTENT = "SHOW_LAT_LONG_INTENT"
  const val INITIAL_LATITUDE_INTENT = "INITIAL_LATITUDE_INTENT"
  const val INITIAL_LONGITUDE_INTENT = "INITIAL_LONGITUDE_INTENT"
  const val INITIAL_ZOOM_INTENT = "INITIAL_ZOOM_INTENT"
  const val ADDRESS_REQUIRED_INTENT = "ADDRESS_REQUIRED_INTENT"
  const val HIDE_MARKER_SHADOW_INTENT = "HIDE_MARKER_SHADOW_INTENT"
  const val MARKER_DRAWABLE_RES_INTENT = "MARKER_DRAWABLE_RES_INTENT"
  const val MARKER_COLOR_RES_INTENT = "MARKER_COLOR_RES_INTENT"
  const val FAB_COLOR_RES_INTENT = "FAB_COLOR_RES_INTENT"
  const val PRIMARY_TEXT_COLOR_RES_INTENT = "PRIMARY_TEXT_COLOR_RES_INTENT"
  const val SECONDARY_TEXT_COLOR_RES_INTENT = "PRIMARY_TEXT_COLOR_RES_INTENT"
  const val MAP_RAW_STYLE_RES_INTENT = "MAP_RAW_STYLE_RES_INTENT"
  const val MAP_TYPE_INTENT: String="MAP_TYPE_INTENT"
  const val ONLY_COORDINATES_INTENT: String="ONLY_COORDINATES_INTENT"
  const val DISABLE_BOTTOM_SHEET_ANIMATION_INTENT: String="DISABLE_BOTTOM_SHEET_ANIMATION_INTENT"
  const val DEFAULT_LATITUDE = 40.748672
  const val DEFAULT_LONGITUDE = -73.985628
  const val DEFAULT_ZOOM = 14.0F
  const val PLACE_PICKER_REQUEST = 100
  const val ADDRESS_INTENT = "ADDRESS_INTENT"
}