package com.sucho.placepicker

object Constants {
  const val SHOW_LAT_LONG_INTENT = "SHOW_LAT_LONG_INTENT"
  const val INITIAL_LATITUDE_INTENT = "INITIAL_LATITUDE_INTENT"
  const val INITIAL_LONGITUDE_INTENT = "INITIAL_LONGITUDE_INTENT"
  const val INITIAL_ZOOM_INTENT = "INITIAL_ZOOM_INTENT"
  const val ADDRESS_REQUIRED_INTENT = "ADDRESS_REQUIRED_INTENT"
  const val HIDE_MARKER_SHADOW_INTENT = "HIDE_MARKER_SHADOW_INTENT"
  const val DEFAULT_LATITUDE = 40.748672
  const val DEFAULT_LONGITUDE = -73.985628
  const val DEFAULT_ZOOM = 14.0F
  const val PLACE_PICKER_REQUEST = 100
  const val ADDRESS_INTENT = "ADDRESS_INTENT"
}